FROM ubuntu:latest
EXPOSE 8080
RUN mkdir -p /mnt/filemanger
RUN apt update && apt install -y curl wget zip unzip
RUN apt-get clean && rm -rf /var/lib/apt/lists /var/cache/apt/archives
RUN wget -O /mnt/filemanger/linux-amd64-filebrowser.tar.gz https://github.com/filebrowser/filebrowser/releases/latest/download/linux-amd64-filebrowser.tar.gz && tar -zxvf /mnt/filemanger/linux-amd64-filebrowser.tar.gz && chmod 775 -R /mnt/filemanger
CMD cd /mnt/filemanger && /mnt/filemanger/filebrowser -a 0.0.0.0 -p 8080
