FROM ubuntu:latest
EXPOSE 8080
RUN mkdir -p /opt/filemanger
WORKDIR /opt/filemanger
RUN apt update && apt install -y curl wget zip unzip openssh
RUN apt-get clean && rm -rf /var/lib/apt/lists /var/cache/apt/archives
RUN wget -O /opt/filemanger/linux-amd64-filebrowser.tar.gz https://github.com/filebrowser/filebrowser/releases/latest/download/linux-amd64-filebrowser.tar.gz && tar -zxvf /opt/filemanger/linux-amd64-filebrowser.tar.gz && chmod 775 /opt/filemanger/filebrowser
CMD /opt/filemanger/filebrowser -a 0.0.0.0 -p 8080 ##-r / -d /root/filebrowser.db