FROM bitnami/nginx:1.22-debian-11
USER root
EXPOSE 80
RUN mkdir -p /app
#WORKDIR /app
ARG NGINX_SERVERNAME
ENV NGINX_SERVERNAME=$NGINX_SERVERNAME
RUN apt update && apt install -y curl wget zip unzip ca-certificates
RUN apt-get clean && rm -rf /var/lib/apt/lists /var/cache/apt/archives
ADD nginx/my_server_block.conf /root/my_server_block.conf
RUN sed -i 's/##Changeme##/"$NGINX_SERVERNAME"/g' /root/my_server_block.conf && cat /root/my_server_block.conf
RUN chmod 775 /root/my_server_block.conf && mv /root/my_server_block.conf /opt/bitnami/nginx/conf/server_blocks/my_server_block.conf
