services:
    web:
        build:
            context: .
            dockerfile: Dockerfile-nginx
            args:
                - NGINX_SERVERNAME:${NGINX_SERVERNAME}
        ports:
            - "80:80"
        volumes:
            - web:/app
        depends_on:
            php:
                condition: service_healthy
    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        ports:
            - "9000"
        volumes:
            - web:/app
    file:
        build:
            context: .
            dockerfile: Dockerfile-filemanger
            args:
                - FILE_USER=${FILE_USER}
                - FILE_PASSWORD=${FILE_PASSWORD}
        ports:
            - "8080:8080"
        #environment:
        volumes:
            - web:/app
        depends_on:
            php:
                condition: service_healthy
            web:
                condition: service_healthy
    cloudflare:
        image: cloudflare/cloudflared:latest
        environment:
            - CF_TOKEN=${CF_TOKEN}   
        entrypoint: cloudflared tunnel --no-autoupdate run --token ${CF_TOKEN}
        depends_on:
            php:
                condition: service_healthy
            web:
                condition: service_healthy
            file:
                condition: service_healthy
volumes:
    web:
        driver_opts:
            size: ${DATA_SIZE}     
