FROM bitnami/nginx:1.22-debian-11
ARG 1NGINX_SERVERNAME
ENV 1NGINX_SERVERNAME=$1NGINX_SERVERNAME
USER root
EXPOSE 80
RUN mkdir -p /app
#WORKDIR /app
RUN apt update && apt install -y curl wget zip unzip ca-certificates
RUN apt-get clean && rm -rf /var/lib/apt/lists /var/cache/apt/archives
ADD nginx/my_server_block.conf /root/my_server_block.conf
RUN echo $1NGINX_SERVERNAME && sed -i "s/##Changeme##/$1NGINX_SERVERNAME/g" /root/my_server_block.conf && cat /root/my_server_block.conf
RUN chmod 775 /root/my_server_block.conf && mv /root/my_server_block.conf /opt/bitnami/nginx/conf/server_blocks/my_server_block.conf
