FROM ubuntu:latest
EXPOSE 8080
ARG FILE_USER
ARG FILE_PASSWORD
ENV FILE_USER=$FILE_USER
ENV FILE_PASSWORD=$FILE_PASSWORD
RUN mkdir -p /mnt/filemanger
RUN apt update && apt install -y curl wget zip unzip ca-certificates software-properties-common gnupg gnupg2 apt-transport-https tzdata
#RUN ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo Asia/Shanghai > /etc/timezone \


RUN apt-get clean && rm -rf /var/lib/apt/lists /var/cache/apt/archives
RUN wget -O /mnt/filemanger/linux-amd64-filebrowser.tar.gz https://github.com/filebrowser/filebrowser/releases/latest/download/linux-amd64-filebrowser.tar.gz && tar -zxvf /mnt/filemanger/linux-amd64-filebrowser.tar.gz -C /mnt/filemanger && chmod 775 -R /mnt/filemanger
RUN /mnt/filemanger/filebrowser -d /mnt/filemanger/filebrowser.db config init 
RUN /mnt/filemanger/filebrowser -d /mnt/filemanger/filebrowser.db users add $(echo $FILE_USER | sed $'s/\"//g') $(echo $FILE_PASSWORD | sed $'s/\"//g') --perm.admin
RUN /mnt/filemanger/filebrowser -d /mnt/filemanger/filebrowser.db users update $(echo $FILE_USER | sed $'s/\"//g') --commands wget

CMD /mnt/filemanger/filebrowser -a 0.0.0.0 -d /mnt/filemanger/filebrowser.db -p 8080
