FROM ubuntu:latest
EXPOSE 8080
ARG FILE_USER
ARG FILE_PASSWORD
ENV FILE_USER=$FILE_USER
ENV FILE_PASSWORD=$FILE_PASSWORD
RUN mkdir -p /mnt/filemanger
RUN apt update && apt install -y curl wget zip unzip ca-certificates software-properties-common gnupg gnupg2 apt-transport-https

RUN echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/sury-php.list && wget -qO - https://packages.sury.org/php/apt.gpg | apt-key add -
RUN apt update && apt install -y php8.1 php8.1-common libapache2-mod-php8.1 php8.1-cli
RUN wget https://getcomposer.org/download/latest-stable/composer.phar \
    && mv composer.phar /usr/local/bin/composer

RUN apt-get clean && rm -rf /var/lib/apt/lists /var/cache/apt/archives
RUN wget -O /mnt/filemanger/linux-amd64-filebrowser.tar.gz https://github.com/filebrowser/filebrowser/releases/latest/download/linux-amd64-filebrowser.tar.gz && tar -zxvf /mnt/filemanger/linux-amd64-filebrowser.tar.gz -C /mnt/filemanger && chmod 775 -R /mnt/filemanger
RUN /mnt/filemanger/filebrowser -d /mnt/filemanger/filebrowser.db config init 
RUN /mnt/filemanger/filebrowser -d /mnt/filemanger/filebrowser.db users add $FILE_USER $FILE_PASSWORD --perm.admin

CMD /mnt/filemanger/filebrowser -a 0.0.0.0 -d /mnt/filemanger/filebrowser.db -p 8080
