name: Sleep Namespace

on:
  repository_dispatch:
  schedule:
    - cron: 50 20 * * *
  workflow_dispatch:
#     inputs:
#       name_space:
#         description: "Name Space"
#         required: false
#         default: ""
#       manual:
#         description: "Name Space"
#         required: true
#         default: "false"
#         type: boolean

env:
  TZ: Asia/Shanghai

jobs:
  Sleep:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Sleep On
        run: |
          wget -qO ~/okteto https://github.com/okteto/okteto/releases/download/2.16.3/okteto-Linux-x86_64
          chmod 775 ~/okteto
          ~/okteto context use https://cloud.okteto.com --token ${{ secrets.OKTETO_TOKEN }}
          ~/okteto namespace list
          ~/okteto namespace sleep ${{ secrets.name_space }}

